[package]
name = "statics"
version = "0.3.4"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["mime03"] }

[dependencies]
mime = "~0.3"
