[package]
name = "statics"
version = "0.3.10"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["mime02"] }

[dependencies]
mime = "0.2.6"
