language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.23.0
  - 1.24.1
  - 1.25.0
  - 1.26.2
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: nightly
     env: TASK=rustfmt
     before_script:
      - rustup component add rustfmt-preview
     script:
      - cargo fmt -- --check
      - cd examples/simple && cargo fmt -- --check
      - cd ../statics && cargo fmt -- --check
      - cd ../static-sass && cargo fmt -- --check
      - cd ../mime03 && cargo fmt -- --check
      - cd ../iron && cargo fmt -- --check
      - cd ../nickel && cargo fmt -- --check
      - cd ../gotham && cargo fmt -- --check
      - cd ../warp && cargo fmt -- --check
   - rust: stable
     env: TASK=iron
     script: cd examples/iron && cargo test
   - rust: stable
     env: TASK=nickel
     script: cd examples/nickel && cargo test
   - rust: stable
     env: TASK=gotham
     script: cd examples/gotham && cargo test
   - rust: stable
     env: TASK=warp
     script: cd examples/warp && cargo test
  allow_failures:
    - rust: nightly
      env:
script:
- |
  cargo build &&
  cargo test &&
  (cd examples/simple && cargo test) &&
  (cd examples/statics && cargo test) &&
  (cd examples/static-sass && cargo test)
