language: rust
rust:
  - stable
  - 1.31.1
  - 1.30.1
  - 1.29.0
  - 1.28.0
  - 1.27.2
  - 1.26.2
  - beta
  - nightly
matrix:
  include:
   - rust: stable
     env: TASK=rustfmt
     before_script:
      - rustup component add rustfmt
     script:
      - cargo fmt -- --check
      - cd examples/simple && cargo fmt -- --check
      - cd ../statics && cargo fmt -- --check
      - cd ../static-sass && cargo fmt -- --check
      - cd ../iron && cargo fmt -- --check
      - cd ../nickel && cargo fmt -- --check
      - cd ../gotham && cargo fmt -- --check
      - cd ../warp && cargo fmt -- --check
   - rust: stable
     env:
      - EXAMPLE=ed2018
      - EXAMPLE=static-sass
      - EXAMPLE=warp
      - EXAMPLE=gotham
      - EXAMPLE=nickel
      - EXAMPLE=iron
     script: cd examples/$EXAMPLE && cargo test
  allow_failures:
    - rust: nightly
      env:
script:
 - cargo build && cargo test
 - cd examples/simple && cargo test
 - cd ../statics && cargo test
