language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.15.1
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: stable
     env: TASK=rustfmt
     script: cargo install -f rustfmt && PATH=${HOME}/.cargo/bin:$PATH cargo fmt
  allow_failures:
    - rust: nightly
script:
- |
  cargo build &&
  cargo test &&
  (cd examples/simple && cargo test) &&
  (cd examples/statics && cargo test) &&
  (cd examples/static-sass && cargo test)
