language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.18.0
  - 1.19.0
  - 1.20.0
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: stable
     env: TASK=rustfmt
     before_script: cargo install -f rustfmt --vers=0.8.6
     script: PATH=${HOME}/.cargo/bin:$PATH cargo fmt
   - rust: stable
     env: TASK=iron
     script: cd examples/iron && cargo test
   - rust: stable
     env: TASK=nickel
     script: cd examples/nickel && cargo test
  allow_failures:
    - rust: nightly
script:
- |
  cargo build &&
  cargo test &&
  (cd examples/simple && cargo test) &&
  (cd examples/statics && cargo test) &&
  (cd examples/static-sass && cargo test)
