language: rust
cache: cargo
before_script:
- cargo update || true
- cargo install -f rustfmt
rust:
  - 1.14.0
  - 1.15.1
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
- |
  PATH=${HOME}/.cargo/bin:$PATH cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test &&
  (cd examples/simple && cargo test) &&
  (cd examples/statics && cargo test) &&
  (cd examples/static-sass && cargo test)
