language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - 1.18.0
  - 1.19.0
  - 1.20.0
  - 1.21.0
  - stable
  - beta
  - nightly
matrix:
  include:
   - rust: nightly
     env: TASK=rustfmt
     before_script:
      - export PATH="$PATH:$HOME/.cargo/bin"
      - CFG_RELEASE_CHANNEL=nightly cargo install -f rustfmt-nightly
     script:
      - cargo fmt -- --unstable-features --write-mode=diff
      - cd examples/simple && cargo fmt -- --unstable-features --write-mode=diff
   - rust: stable
     env: TASK=iron
     script: cd examples/iron && cargo test
   - rust: stable
     env: TASK=nickel
     script: cd examples/nickel && cargo test
  allow_failures:
    - rust: nightly
script:
- |
  cargo build &&
  cargo test &&
  (cd examples/simple && cargo test) &&
  (cd examples/statics && cargo test) &&
  (cd examples/static-sass && cargo test)
