[package]
name = "ructe"
version = "0.1.2"
authors = ["Rasmus Kaj <kaj@kth.se>"]
description = "Rust Compiled Templates, a build-time template system"
repository = "https://github.com/kaj/ructe"
keywords = ["template", "html"]
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
md5 = "^0.3"
nom = "^1"
rustc-serialize = "^0.3"
