[package]
name = "ructe"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]
description = "Rust Compiled Templates, a build-time template system"
repository = "https://github.com/kaj/ructe"
keywords = ["template", "html"]
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
nom = { version = "*", features = ["regexp"] }
regex = "*"
