[package]
name = "ructe"
version = "0.3.5-PRE"
authors = ["Rasmus Kaj <kaj@kth.se>"]
description = "Rust Compiled Templates, efficient type-safe templates."
documentation = "https://docs.rs/ructe"
repository = "https://github.com/kaj/ructe"
readme = "README.md"
keywords = ["web", "templating", "html"]
categories = ["template-engine", "web-programming"]
license = "MIT/Apache-2.0"

[features]
sass = ["rsass"]
mime02 = []
mime03 = []

[dependencies]
base64 = "^0.7.0"
lazy_static = "^0.2"
md5 = "^0.3"
nom = { version = "^3.2", features = ["verbose-errors"] }

rsass = { version = "^0.3.4", optional = true }

[badges]
travis-ci = { repository = "kaj/ructe" }
