[package]
name = "ructe"
version = "0.2.5"
authors = ["Rasmus Kaj <kaj@kth.se>"]
description = "Rust Compiled Templates, a build-time template system"
documentation = "https://docs.rs/ructe"
repository = "https://github.com/kaj/ructe"
keywords = ["template", "html"]
readme = "README.md"
license = "MIT/Apache-2.0"

[dependencies]
base64 = "^0.3"
lazy_static = "^0.2"
md5 = "^0.3"
nom = { version = "^2", features = ["verbose-errors"] }
