[package]
name = "iron-ructe"
version = "0.3.6"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { path = "../..", features = ["sass", "mime02"] }

[dependencies]
iron = "~0.5"
router = "~0.5"
mime = "~0.2"
